name: Publish Storybook to Chromatic

on:
  push:
    paths:
      - ui/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # chromatic needs all commits

      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v10
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
